[package]
name = "raytracer"
version = "0.1.0"
authors = ["rodrigovalle <rdan.valle@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.2"
ultraviolet = { version = "0.7", features = ["int", "f64"]}
